version: 1
update_configs:

  # Strategies for "current major release":
  # - weekly check
  # - only security updates of "production" (excludes dev) dependencies
  # - only lockfile updates
  - package_manager: "javascript"
    directory: "/"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
    version_requirement_updates: "off"
    update_schedule: "weekly"
    target_branch: "9.5/bugfixes"
  - package_manager: "php:composer"
    directory: "/"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
    version_requirement_updates: "off"
    update_schedule: "weekly"
    target_branch: "9.5/bugfixes"

  # Strategies for "future major release":
  # - monthly check
  # - allow version increase in package.json / composer.json
  - package_manager: "javascript"
    directory: "/"
    version_requirement_updates: "increase_versions_if_necessary"
    update_schedule: "monthly"
    target_branch: "master"
  - package_manager: "php:composer"
    directory: "/"
    version_requirement_updates: "increase_versions_if_necessary"
    update_schedule: "monthly"
    target_branch: "master"
